### ISSUE TITLE
Export tables separately

### ISSUE THREAD

**Issue by renathu** [adriancs2/MySqlBackup.Net#1]
Good afternoon, I would like to know if there is how to export the tables separately, does each table generate its file?

**Comment by adriancs2** [comment]
You can choose to export each table in separate file or conditional export. You can have a look at this [documentation](http://mysqlbackupnet.codeplex.com/wikipage?title=Conditional%20Rows%20Export%20for%20Each%20Table&referringTitle=Documentation) and see whether your problem get solved or not.
