### ISSUE TITLE
About moving CodePlex articles

### ISSUE THREAD

**Issue by hejiheji001** [adriancs2/MySqlBackup.Net#2]
As you may know, CodePlex is shutting down this year.

Is it possible for you to move the articles to Github?

Thank you very much.

**Comment by adriancs2** [comment]
Yeah, I agree with you. I'm kinda busy at the moment. I will try to do copy the documentation/articles from Codeplex to Github. thanks for you suggestions 👍 :)

**Comment by adriancs2** [comment]
Oh ya, by the way, would you help to copy the articles from codeplex to github(here)? :)

**Comment by ManuelOcana** [comment]
Is this useful to you? I copied and pasted them in a .docx
[Documentation MySQLBackupNet.docx](https://github.com/adriancs2/MySqlBackup.Net/files/1167164/Documentation.MySQLBackupNet.docx)

**Comment by adriancs2** [comment]
Hi ManuelOcana, thanks for your effort for doing the DOCX file.
It actually did not help.
The content has to be added into the [Wiki] page of this site.

It makes no different between 
[copy paste from "CodePlex to Github"]
and
[copy paste from "DOCX file to Github"]

It's ok. I will find another time to this work. Stay tune... :)

**Comment by ManuelOcana** [comment]
Don't worry man, I did it to have an offline reference while testing your nice project, I'm fairly new to github and I don't really know how to add or edit articles here, I will look it up in case I can help in any way.

**Comment by adriancs2** [comment]
Ok guys, I have already moved the documentation from Codeplex.com to Github.com. Now you can go to the "Wiki" page to read the documentation :) cheers
